name: number_trivia
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: any
  # Bloc for state management
  flutter_bloc: ^7.2.0
  # Value equality
  equatable: 2.0.3
  # Functional programing thingies
  dartz: any
  # Remote API
  data_connection_checker_tv: ^0.3.5-nullsafety
  http: any
  # Local cache
  shared_preferences: ^2.0.7

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any
  build_runner: any
flutter:

  uses-material-design: true

